INSERT INTO TB_AGENCIA (ADDRESS, LATITUDE, LONGITUDE, NAME) VALUES ('Rua A', -9.0, -18.0, 'Local A');
INSERT INTO TB_AGENCIA (ADDRESS, LATITUDE, LONGITUDE, NAME) VALUES ('Rua B', -6.0, -1.0, 'Local B');
INSERT INTO TB_AGENCIA (ADDRESS, LATITUDE, LONGITUDE, NAME) VALUES ('Rua C', -9.0, -18.0, 'Local C');
INSERT INTO TB_AGENCIA (ADDRESS, LATITUDE, LONGITUDE, NAME) VALUES ('Rua D', -6.0, -1.0, 'Local D');
INSERT INTO TB_AGENCIA (ADDRESS, LATITUDE, LONGITUDE, NAME) VALUES ('Rua E', -9.0, -18.0, 'Local E');
INSERT INTO TB_AGENCIA (ADDRESS, LATITUDE, LONGITUDE, NAME) VALUES ('Rua F', -6.0, -1.0, 'Local F');
